### PR TITLE
Replace the begin invoke with a Task to have portable .NetCore compat…

### PR DESCRIPTION
**Pull request by godboutj**
…ibility at runtime. Use https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types#from-tap-to-apm as reference.

This help use the async publish on non Full .NET library. Not sure the AsyncCallback was ever used, but should still be fully compatible.

### CODE REVIEW

**Comment by mxjones** [comment]
Thanks for this!

**Comment by godboutj** [comment]
No problem, for true async on .NET Core you should probably allow the following:
`public Task<TEventBase> PublishAsync<TEventBase>(TEventBase eventItem) where TEventBase : EvenBase
{
  return Task.Run(() => Publish(eventItem));
}`

This allow for await and cancel token etc. That would be the right way for Task I think. Maybe a PublishTask() would be a better naming.

**Comment by mxjones** [comment]
Yeah agreed - I did have a look a while ago at what it would take to refactor to use async/await but then I got busy with other things/work 

Would possibly be breaking changes, so a new major version - but is definitely something I would like to do at some point.

**Comment by godboutj** [comment]
Only use the above as PublishTask() and deprecate the old PublishAsync() call. That would keep the backward compatiblility and that's about it. I did myself a wrapper on top of RedBus to have scope subscribe, wait on particular event and event on subscribe started and stopped. I just added that function and got ride of the old PublishAsync usage in the end. The merged fix was to at least port directly from Full .NET to .NET Core.  Good lib by the way, simple yet work as expected.

**Pull request merged**
