### PR TITLE
WeakReference in Subscription

### PR DESCRIPTION
**Pull request by turboslon**
Implemented WeakReference in Subscription Class:
* Implemented
* Added tests that subscription doesn't hold subscribed object
* Updated README.MD

### CODE REVIEW

**Comment by turboslon** [comment]
Hi guys! 
It's my first PR, so please let me know what's wrong with it.
I didn't touch Redbus.nuspec (package version is still 1.0.4)

**Comment by mxjones** [comment]
Hi,

Thanks for contributing, this looks great! I will take a closer look tomorrow.

Cheers

**Comment by turboslon** [comment]
It's an unpleasant surprise for me that newly pushed checkin (DefaultInstance for EventBus Added) somehow added to this PR. It's unplanned =) 
I'm very sorry! Next time I'll create a separate branch for PR...

**Comment by mxjones** [comment]
That's no problem, had a look and all seems good - so thanks for this PR. I will look at getting this merged and a new NuGet package released on Monday.

**Pull request closed without merging**
